kind: pipeline
type: docker
name: Build

trigger:
  event:
    - push
  branch:
    - develop

steps:
  - name: build
    image: docker:27.2.0-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - cd streamlit_app
      - docker build -f dockerfile .
      - cd ../webhook_server
      - docker build -f dockerfile .
      - cd ..
      - echo "Build completed successfully"
services:
  - name: dind
    image: docker:27.1-dind
    privileged: true

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: Publish

trigger:
  event:
    - push
  branch:
    - develop

depends_on:
  - Build

steps:
  - name: publish
    image: docker:27.2.0-dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      GITHUB_USERNAME:
        from_secret: GITHUB_USERNAME
      GITHUB_TOKEN:
        from_secret: GHCR_TOKEN
    commands:
      - echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - cd webhook_server
      - docker build -t ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai-hook:${DRONE_COMMIT_BRANCH} -f dockerfile .
      - docker push ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai-hook:${DRONE_COMMIT_BRANCH}
      - cd ../streamlit_app
      - docker build -t ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai:${DRONE_COMMIT_BRANCH} -f dockerfile .
      - docker push ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai:${DRONE_COMMIT_BRANCH}
      - cd ..
      - echo "Publish completed successfully"

      


services:
  - name: dind
    image: docker:27.1-dind
    privileged: true

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: Deploy

trigger:
  event:
    - push
  branch:
    - develop

depends_on:
  - Publish

steps:
  - name: deploy-stage
    image: docker:27.2.0-cli
    privileged: true
    environment:
      GITHUB_USERNAME:
        from_secret: GITHUB_USERNAME
      GITHUB_TOKEN:
        from_secret: GHCR_TOKEN
      DRONE_TAG: ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA}
    volumes:
      - name: dockersock
        host:
         path: /var/run/docker.sock  
    commands:
      - apk add --no-cache git wget docker
      # - apk add --no-cache git wget
      - wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/local/bin/yq
      - chmod +x /usr/local/bin/yq
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - docker pull ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai-hook:develop
      - docker pull ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai:develop
      - git clone https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/leds-conectafapes/leds-conectafapes-infra.git
      - cd leds-conectafapes-infra/services/Requirements-AI
      - DIGEST_WEBHOOK=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai-hook:develop | cut -d'@' -f2)
      - DIGEST_AI=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai:develop | cut -d'@' -f2)
      - yq -i '.spec.template.spec.containers[0].image = "ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai-hook@'"$DIGEST_WEBHOOK"'' deployment.yaml
      - yq -i '.spec.template.spec.containers[1].image = "ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai@'"$DIGEST_AI"'' deployment.yaml
      - echo "Deployment images updated successfully"
      - git config user.name "drone-ci"
      - git config user.email "drone@ci.leds"
      - git add deployment.yaml
      - git commit -m "[DEPLOY] Atualizando imagens para ${DRONE_TAG}"
      - git push 
when:
    branch:
      include:
        - develop
      