version: '3.9'
services:

  # streamlit_app:
  #   build: ./streamlit_app
  #   env_file:
  #     - ./streamlit_app/.env
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./shared/uploads:/app/shared/uploads
  #     - ./pyproject.toml:/app/pyproject.toml
  #   depends_on:
  #     - webhook_server
  #   networks:
  #     - lang_net

  rai_frontend:
    build: ./frontend
    env_file: 
      - ./frontend/.env
    ports:
      - "80:80"
    volumes:
      - ./shared/uploads:/app/shared/uploads
    networks:
      - lang_net

  rai_backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./shared/uploads:/app/shared/uploads
      - sqlite_data:/app/backend/db.sqlite3
    networks:
      - lang_net

volumes:
  sqlite_data:
      
networks:
  lang_net:
    driver: bridge
