version: "3.9"

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: rai
      POSTGRES_USER: rai
      POSTGRES_PASSWORD: rai123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: