[project]
name = "RequirementsAI"
version = "0.5.0"
description = """
Software requirements extraction pipeline from video interviews, utilizing
Natural Language Models (LLMs), LangGraph, specialized agents, and a
user-friendly Streamlit interface.
"""
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "commitizen>=3.21.0"
]

[tool.commitizen]
name = "cz_conventional_commits"
version_provider = "pep621"
tag_format = "v$version"
update_changelog_on_bump = true
version_files = [
    "pyproject.toml:^version",
]