FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app_streamlit_docker.py .

# IMPORTANTE: o diretório 'shared/uploads' NÃO precisa ser copiado,
# pois o volume será montado em /app/shared/uploads via docker-compose.
# Mas se quiser criar vazio no build, adicione a linha abaixo:
# RUN mkdir -p shared/uploads

CMD ["streamlit", "run", "app_streamlit_docker.py", "--server.port=8501", "--server.address=0.0.0.0"]
