# Generated by Django 5.2.7 on 2026-01-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'modulo',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vMajor', models.IntegerField(blank=True, null=True)),
                ('vMinor', models.IntegerField(blank=True, null=True)),
                ('geradoIA', models.BooleanField(blank=True, null=True)),
                ('arquivo', models.TextField(blank=True, null=True)),
                ('origemAudio', models.CharField(blank=True, null=True)),
                ('TipoDocumento', models.CharField(choices=[('MINIMUNDO', 'Minimundo'), ('REQUISITOS', 'Requisitos'), ('CASO_USO', 'Caso uso'), ('DIAGRAMA_CLASSE', 'Diagrama classe'), ('PROTOTIPO_INTERFACE', 'Prototipo interface')], default='MINIMUNDO', max_length=20)),
                ('DocumentoAnterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documento_%(class)s_anteior', to='apps_classes.documento')),
                ('DocumentoOrigem', models.ManyToManyField(blank=True, null=True, related_name='documento_%(class)s_origem', to='apps_classes.documento')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('Modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulo_%(class)s', to='apps_classes.modulo')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
        migrations.AddField(
            model_name='modulo',
            name='Projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeto_%(class)s', to='apps_classes.projeto'),
        ),
    ]
