# Generated by Django 5.2.7 on 2026-03-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_classes', '0002_documento_user_modulo_user_projeto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='origemAudio',
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivoAudio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
