# Generated by Django 5.2.7 on 2026-04-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_classes', '0003_remove_documento_origemaudio_documento_arquivoaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='vMaisRecente',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
