# Generated by Django 5.2.7 on 2026-04-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_classes', '0004_documento_vmaisrecente'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='obsoleto',
            field=models.BooleanField(default=False),
        ),
    ]
