name: Requirements AI CI/CD

on:
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop"]

permissions:
  contents: write
  packages: write

concurrency:
  group: requirements-ai-${{ github.ref_name }}-${{ github.event_name }}
  cancel-in-progress: false

env:
  IMAGE_FRONTEND: ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai-frontend
  IMAGE_BACKEND: ghcr.io/leds-conectafapes/leds-conectafapes-requirementsai-backend
  INFRA_REPO: leds-conectafapes/leds-conectafapes-infra
  BRANCH_NAME: ${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    name: Build Check
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Pre-clean workspace
        run: sudo rm -rf "$GITHUB_WORKSPACE"/.??* "$GITHUB_WORKSPACE"/* || true

      - uses: actions/checkout@v6

      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER "$GITHUB_WORKSPACE" || true

      - name: Prepare Frontend .env
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
             BASE_URL="https://backend-rai.leds.dev.br"
          else
             BASE_URL="https://backend-rai.leds.dev.br"
          fi
          
          OAUTH_CLIENT_ID=${{ secrets.CLIENT_ID }}

          echo "VITE_BACKEND_ADMIN_BASE_URL=${BASE_URL}/" >> ./frontend/.env
          echo "VITE_CLIENT_ID=${OAUTH_CLIENT_ID}" >> ./frontend/.env


      - name: Build Frontend Docker image check
        run: docker build -f ./frontend/Dockerfile ./frontend 

      - name: Build Backend Docker image check
        run: docker build -f ./backend/Dockerfile ./backend 

  publish:
    name: Publish (GHCR)
    runs-on: [self-hosted, linux, x64]
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Pre-clean workspace
        run: sudo rm -rf "$GITHUB_WORKSPACE"/.??* "$GITHUB_WORKSPACE"/* || true

      - uses: actions/checkout@v6

      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER "$GITHUB_WORKSPACE" || true

      - name: Prepare Frontend .env
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
             BASE_URL="https://backend-rai.leds.dev.br"
          else
             BASE_URL="https://backend-rai.leds.dev.br"
          fi
          
          OAUTH_CLIENT_ID=${{ secrets.CLIENT_ID }}

          echo "VITE_BACKEND_ADMIN_BASE_URL=${BASE_URL}/" >> ./frontend/.env
          echo "VITE_CLIENT_ID=${OAUTH_CLIENT_ID}" >> ./frontend/.env

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend
        run: |
          FULL_IMAGE_FRONTEND="${IMAGE_FRONTEND}:${BRANCH_NAME}"
          docker build --no-cache -t $FULL_IMAGE_FRONTEND -f ./frontend/Dockerfile ./frontend
          docker push $FULL_IMAGE_FRONTEND

      - name: Build & Push Backend
        run: |
          FULL_IMAGE_BACKEND="${IMAGE_BACKEND}:${BRANCH_NAME}"
          docker build --no-cache -t $FULL_IMAGE_BACKEND -f ./backend/Dockerfile ./backend
          docker push $FULL_IMAGE_BACKEND

  deploy:
    name: Deploy (Infra repo)
    runs-on: [self-hosted, linux, x64]
    needs: publish
    if: github.event_name == 'push' && (github.ref_name == 'develop' || github.ref_name == 'main')
    steps:
      - name: Determine target path
        id: envpath
        run: |
          case "${BRANCH_NAME}" in
            develop) ENV_PATH="agentes/stage/Requirements-AI" ;;
            *) echo "Branch não mapeada"; exit 1 ;;
          esac

          echo "env_path=${ENV_PATH}" >> $GITHUB_OUTPUT
          echo "target_branch=develop" >> $GITHUB_OUTPUT  

      - name: Checkout infra repository
        uses: actions/checkout@v6
        with:
          repository: ${{ env.INFRA_REPO }}
          token: ${{ secrets.INFRA_PUSH_TOKEN }}
          ref: ${{ steps.envpath.outputs.target_branch }}
          path: infra

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update deployment.yaml
        working-directory: infra/${{ steps.envpath.outputs.env_path }}
        run: |
          FULL_IMAGE_FRONTEND="${IMAGE_FRONTEND}:${BRANCH_NAME}"
          FULL_IMAGE_BACKEND="${IMAGE_BACKEND}:${BRANCH_NAME}"
          
          docker pull $FULL_IMAGE_FRONTEND
          docker pull $FULL_IMAGE_BACKEND
          
          DIGEST_FRONTEND=$(docker inspect --format='{{index .RepoDigests 0}}' $FULL_IMAGE_FRONTEND | cut -d'@' -f2)
          DIGEST_BACKEND=$(docker inspect --format='{{index .RepoDigests 0}}' $FULL_IMAGE_BACKEND | cut -d'@' -f2)
          
          sed -i -E "s|^([[:space:]]*)image:.*frontend.*|\1image: ${IMAGE_FRONTEND}@${DIGEST_FRONTEND}|" frontend/deployment.yaml
          sed -i -E "s|^([[:space:]]*)image:.*backend.*|\1image: ${IMAGE_BACKEND}@${DIGEST_BACKEND}|" backend/deployment.yaml
          sed -i -E "s|^([[:space:]]*)image:.*requirementsai-backend.*|\1image: ${IMAGE_BACKEND}@${DIGEST_BACKEND}|" celery/deployment.yaml

      - name: Commit and push changes
        working-directory: infra
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[DEPLOY] Requirements AI (${BRANCH_NAME}) - SHA: ${COMMIT_SHA:0:7}" || echo "Nenhuma mudança"
          git push origin ${{ steps.envpath.outputs.target_branch }}
